<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\CompanyIndustry;
use Illuminate\Database\Seeder;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get industry IDs
        $technologyId = CompanyIndustry::where('slug', 'technology')->first()?->id;
        $automotiveId = CompanyIndustry::where('slug', 'automotive')->first()?->id;
        $entertainmentId = CompanyIndustry::where('slug', 'entertainment')->first()?->id;
        $retailId = CompanyIndustry::where('slug', 'retail')->first()?->id;
        $foodBeverageId = CompanyIndustry::where('slug', 'food-beverage')->first()?->id;
        $apparelId = CompanyIndustry::where('slug', 'fashion')->first()?->id;
        $bankingId = CompanyIndustry::where('slug', 'banking')->first()?->id;
        $pharmaceuticalsId = CompanyIndustry::where('slug', 'pharmaceuticals')->first()?->id;
        $telecomId = CompanyIndustry::where('slug', 'telecommunications')->first()?->id;
        $energyId = CompanyIndustry::where('slug', 'energy')->first()?->id;
        $aerospaceId = CompanyIndustry::where('slug', 'aerospace')->first()?->id;
        $consultingId = CompanyIndustry::where('slug', 'consulting')->first()?->id;

        $companies = [
            // Technology Companies
            [
                'name' => 'Apple Inc.',
                'industry_id' => $technologyId,
                'email' => 'contact@apple.com',
                'website' => 'apple.com',
                'phone' => '+1 (408) 996-1010',
                'address' => 'One Apple Park Way',
                'city' => 'Cupertino',
                'region' => 'California',
                'postal_code' => '95014',
                'country' => 'United States',
                'employee_count' => 164000,
                'annual_revenue' => 394328000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/apple',
                    'twitter' => '@Apple',
                    'founded_year' => 1976,
                ]),
            ],
            [
                'name' => 'Microsoft Corporation',
                'industry_id' => $technologyId,
                'email' => 'info@microsoft.com',
                'website' => 'microsoft.com',
                'phone' => '+1 (425) 882-8080',
                'address' => 'One Microsoft Way',
                'city' => 'Redmond',
                'region' => 'Washington',
                'postal_code' => '98052',
                'country' => 'United States',
                'employee_count' => 221000,
                'annual_revenue' => 211915000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/microsoft',
                    'twitter' => '@Microsoft',
                    'founded_year' => 1975,
                ]),
            ],
            [
                'name' => 'Google LLC',
                'industry_id' => $technologyId,
                'email' => 'press@google.com',
                'website' => 'google.com',
                'phone' => '+1 (650) 253-0000',
                'address' => '1600 Amphitheatre Parkway',
                'city' => 'Mountain View',
                'region' => 'California',
                'postal_code' => '94043',
                'country' => 'United States',
                'employee_count' => 182502,
                'annual_revenue' => 307394000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/google',
                    'twitter' => '@Google',
                    'founded_year' => 1998,
                ]),
            ],
            [
                'name' => 'Meta Platforms Inc.',
                'industry_id' => $technologyId,
                'email' => 'info@meta.com',
                'website' => 'meta.com',
                'phone' => '+1 (650) 543-4800',
                'address' => '1 Meta Way',
                'city' => 'Menlo Park',
                'region' => 'California',
                'postal_code' => '94025',
                'country' => 'United States',
                'employee_count' => 86482,
                'annual_revenue' => 134902000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/meta',
                    'twitter' => '@Meta',
                    'founded_year' => 2004,
                ]),
            ],
            [
                'name' => 'Amazon.com Inc.',
                'industry_id' => $retailId,
                'email' => 'support@amazon.com',
                'website' => 'amazon.com',
                'phone' => '+1 (206) 266-1000',
                'address' => '410 Terry Avenue North',
                'city' => 'Seattle',
                'region' => 'Washington',
                'postal_code' => '98109',
                'country' => 'United States',
                'employee_count' => 1541000,
                'annual_revenue' => 574785000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/amazon',
                    'twitter' => '@Amazon',
                    'founded_year' => 1994,
                ]),
            ],
            [
                'name' => 'Netflix Inc.',
                'industry_id' => $entertainmentId,
                'email' => 'info@netflix.com',
                'website' => 'netflix.com',
                'phone' => '+1 (408) 540-3700',
                'address' => '121 Albright Way',
                'city' => 'Los Gatos',
                'region' => 'California',
                'postal_code' => '95032',
                'country' => 'United States',
                'employee_count' => 13000,
                'annual_revenue' => 33723000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/netflix',
                    'twitter' => '@Netflix',
                    'founded_year' => 1997,
                ]),
            ],
            [
                'name' => 'IBM Corporation',
                'industry_id' => $technologyId,
                'email' => 'contact@ibm.com',
                'website' => 'ibm.com',
                'phone' => '+1 (914) 499-1900',
                'address' => '1 New Orchard Road',
                'city' => 'Armonk',
                'region' => 'New York',
                'postal_code' => '10504',
                'country' => 'United States',
                'employee_count' => 282100,
                'annual_revenue' => 61860000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/ibm',
                    'twitter' => '@IBM',
                    'founded_year' => 1911,
                ]),
            ],
            [
                'name' => 'Intel Corporation',
                'industry_id' => $technologyId,
                'email' => 'support@intel.com',
                'website' => 'intel.com',
                'phone' => '+1 (408) 765-8080',
                'address' => '2200 Mission College Boulevard',
                'city' => 'Santa Clara',
                'region' => 'California',
                'postal_code' => '95054',
                'country' => 'United States',
                'employee_count' => 124800,
                'annual_revenue' => 54228000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/intel-corporation',
                    'twitter' => '@Intel',
                    'founded_year' => 1968,
                ]),
            ],

            // Automotive Companies
            [
                'name' => 'Tesla Inc.',
                'industry_id' => $automotiveId,
                'email' => 'ir@tesla.com',
                'website' => 'tesla.com',
                'phone' => '+1 (512) 516-8177',
                'address' => '1 Tesla Road',
                'city' => 'Austin',
                'region' => 'Texas',
                'postal_code' => '78725',
                'country' => 'United States',
                'employee_count' => 127855,
                'annual_revenue' => 96773000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/tesla-motors',
                    'twitter' => '@Tesla',
                    'founded_year' => 2003,
                ]),
            ],
            [
                'name' => 'Toyota Motor Corporation',
                'industry_id' => $automotiveId,
                'email' => 'customer@toyota.com',
                'website' => 'toyota.com',
                'phone' => '+81 3-3817-7111',
                'address' => '1 Toyota-cho',
                'city' => 'Toyota',
                'region' => 'Aichi',
                'postal_code' => '471-8571',
                'country' => 'Japan',
                'employee_count' => 375235,
                'annual_revenue' => 274534000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/toyota',
                    'twitter' => '@Toyota',
                    'founded_year' => 1937,
                ]),
            ],
            [
                'name' => 'Ford Motor Company',
                'industry_id' => $automotiveId,
                'email' => 'contact@ford.com',
                'website' => 'ford.com',
                'phone' => '+1 (313) 322-3000',
                'address' => 'One American Road',
                'city' => 'Dearborn',
                'region' => 'Michigan',
                'postal_code' => '48126',
                'country' => 'United States',
                'employee_count' => 173000,
                'annual_revenue' => 176191000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/ford-motor-company',
                    'twitter' => '@Ford',
                    'founded_year' => 1903,
                ]),
            ],
            [
                'name' => 'General Motors',
                'industry_id' => $automotiveId,
                'email' => 'info@gm.com',
                'website' => 'gm.com',
                'phone' => '+1 (313) 667-1500',
                'address' => '100 Renaissance Center',
                'city' => 'Detroit',
                'region' => 'Michigan',
                'postal_code' => '48243',
                'country' => 'United States',
                'employee_count' => 163000,
                'annual_revenue' => 171800000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/general-motors',
                    'twitter' => '@GM',
                    'founded_year' => 1908,
                ]),
            ],

            // Retail Companies
            [
                'name' => 'Walmart Inc.',
                'industry_id' => $retailId,
                'email' => 'corporate@walmart.com',
                'website' => 'walmart.com',
                'phone' => '+1 (479) 273-4000',
                'address' => '702 Southwest 8th Street',
                'city' => 'Bentonville',
                'region' => 'Arkansas',
                'postal_code' => '72716',
                'country' => 'United States',
                'employee_count' => 2100000,
                'annual_revenue' => 648125000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/walmart',
                    'twitter' => '@Walmart',
                    'founded_year' => 1962,
                ]),
            ],
            [
                'name' => 'Target Corporation',
                'industry_id' => $retailId,
                'email' => 'guest.relations@target.com',
                'website' => 'target.com',
                'phone' => '+1 (612) 304-6073',
                'address' => '1000 Nicollet Mall',
                'city' => 'Minneapolis',
                'region' => 'Minnesota',
                'postal_code' => '55403',
                'country' => 'United States',
                'employee_count' => 440000,
                'annual_revenue' => 109120000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/target',
                    'twitter' => '@Target',
                    'founded_year' => 1902,
                ]),
            ],

            // Food & Beverage Companies
            [
                'name' => 'Coca-Cola Company',
                'industry_id' => $foodBeverageId,
                'email' => 'contact@coca-cola.com',
                'website' => 'coca-cola.com',
                'phone' => '+1 (404) 676-2121',
                'address' => 'One Coca-Cola Plaza',
                'city' => 'Atlanta',
                'region' => 'Georgia',
                'postal_code' => '30313',
                'country' => 'United States',
                'employee_count' => 82500,
                'annual_revenue' => 45754000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/the-coca-cola-company',
                    'twitter' => '@CocaCola',
                    'founded_year' => 1892,
                ]),
            ],
            [
                'name' => 'PepsiCo Inc.',
                'industry_id' => $foodBeverageId,
                'email' => 'contact@pepsico.com',
                'website' => 'pepsico.com',
                'phone' => '+1 (914) 253-2000',
                'address' => '700 Anderson Hill Road',
                'city' => 'Purchase',
                'region' => 'New York',
                'postal_code' => '10577',
                'country' => 'United States',
                'employee_count' => 315000,
                'annual_revenue' => 91471000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/pepsico',
                    'twitter' => '@PepsiCo',
                    'founded_year' => 1965,
                ]),
            ],
            [
                'name' => 'Starbucks Corporation',
                'industry_id' => $foodBeverageId,
                'email' => 'info@starbucks.com',
                'website' => 'starbucks.com',
                'phone' => '+1 (206) 447-1575',
                'address' => '2401 Utah Avenue South',
                'city' => 'Seattle',
                'region' => 'Washington',
                'postal_code' => '98134',
                'country' => 'United States',
                'employee_count' => 402000,
                'annual_revenue' => 36176000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/starbucks',
                    'twitter' => '@Starbucks',
                    'founded_year' => 1971,
                ]),
            ],
            [
                'name' => 'McDonald\'s Corporation',
                'industry_id' => $foodBeverageId,
                'email' => 'contact@mcdonalds.com',
                'website' => 'mcdonalds.com',
                'phone' => '+1 (630) 623-3000',
                'address' => '110 North Carpenter Street',
                'city' => 'Chicago',
                'region' => 'Illinois',
                'postal_code' => '60607',
                'country' => 'United States',
                'employee_count' => 200000,
                'annual_revenue' => 25494000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/mcdonalds',
                    'twitter' => '@McDonalds',
                    'founded_year' => 1940,
                ]),
            ],

            // Fashion/Apparel Companies
            [
                'name' => 'Nike Inc.',
                'industry_id' => $apparelId,
                'email' => 'help@nike.com',
                'website' => 'nike.com',
                'phone' => '+1 (503) 671-6453',
                'address' => 'One Bowerman Drive',
                'city' => 'Beaverton',
                'region' => 'Oregon',
                'postal_code' => '97005',
                'country' => 'United States',
                'employee_count' => 83700,
                'annual_revenue' => 51217000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/nike',
                    'twitter' => '@Nike',
                    'founded_year' => 1964,
                ]),
            ],
            [
                'name' => 'Adidas AG',
                'industry_id' => $apparelId,
                'email' => 'service@adidas.com',
                'website' => 'adidas.com',
                'phone' => '+49 9132 84-0',
                'address' => 'Adi-Dassler-Strasse 1',
                'city' => 'Herzogenaurach',
                'region' => 'Bavaria',
                'postal_code' => '91074',
                'country' => 'Germany',
                'employee_count' => 59000,
                'annual_revenue' => 22311000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/adidas',
                    'twitter' => '@adidas',
                    'founded_year' => 1949,
                ]),
            ],

            // Banking Companies
            [
                'name' => 'JPMorgan Chase & Co.',
                'industry_id' => $bankingId,
                'email' => 'customer.service@jpmchase.com',
                'website' => 'jpmorganchase.com',
                'phone' => '+1 (212) 270-6000',
                'address' => '383 Madison Avenue',
                'city' => 'New York',
                'region' => 'New York',
                'postal_code' => '10179',
                'country' => 'United States',
                'employee_count' => 309926,
                'annual_revenue' => 158100000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/jpmorganchase',
                    'twitter' => '@JPMorgan',
                    'founded_year' => 1799,
                ]),
            ],
            [
                'name' => 'Bank of America',
                'industry_id' => $bankingId,
                'email' => 'customer.service@bankofamerica.com',
                'website' => 'bankofamerica.com',
                'phone' => '+1 (704) 386-5681',
                'address' => '100 North Tryon Street',
                'city' => 'Charlotte',
                'region' => 'North Carolina',
                'postal_code' => '28255',
                'country' => 'United States',
                'employee_count' => 213000,
                'annual_revenue' => 94900000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/bank-of-america',
                    'twitter' => '@BankofAmerica',
                    'founded_year' => 1904,
                ]),
            ],

            // Pharmaceuticals Companies
            [
                'name' => 'Pfizer Inc.',
                'industry_id' => $pharmaceuticalsId,
                'email' => 'contact@pfizer.com',
                'website' => 'pfizer.com',
                'phone' => '+1 (212) 733-2323',
                'address' => '66 Hudson Boulevard East',
                'city' => 'New York',
                'region' => 'New York',
                'postal_code' => '10001',
                'country' => 'United States',
                'employee_count' => 83000,
                'annual_revenue' => 58496000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/pfizer',
                    'twitter' => '@Pfizer',
                    'founded_year' => 1849,
                ]),
            ],
            [
                'name' => 'Johnson & Johnson',
                'industry_id' => $pharmaceuticalsId,
                'email' => 'info@its.jnj.com',
                'website' => 'jnj.com',
                'phone' => '+1 (732) 524-0400',
                'address' => 'One Johnson & Johnson Plaza',
                'city' => 'New Brunswick',
                'region' => 'New Jersey',
                'postal_code' => '08933',
                'country' => 'United States',
                'employee_count' => 152700,
                'annual_revenue' => 85159000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/johnson-johnson',
                    'twitter' => '@JNJNews',
                    'founded_year' => 1886,
                ]),
            ],

            // Telecommunications Companies
            [
                'name' => 'Verizon Communications',
                'industry_id' => $telecomId,
                'email' => 'info@verizon.com',
                'website' => 'verizon.com',
                'phone' => '+1 (212) 395-1000',
                'address' => '1095 Avenue of the Americas',
                'city' => 'New York',
                'region' => 'New York',
                'postal_code' => '10036',
                'country' => 'United States',
                'employee_count' => 105400,
                'annual_revenue' => 134000000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/verizon',
                    'twitter' => '@Verizon',
                    'founded_year' => 1983,
                ]),
            ],
            [
                'name' => 'AT&T Inc.',
                'industry_id' => $telecomId,
                'email' => 'contact@att.com',
                'website' => 'att.com',
                'phone' => '+1 (210) 821-4105',
                'address' => 'Whitacre Tower, 208 S. Akard Street',
                'city' => 'Dallas',
                'region' => 'Texas',
                'postal_code' => '75202',
                'country' => 'United States',
                'employee_count' => 160700,
                'annual_revenue' => 122000000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/att',
                    'twitter' => '@ATT',
                    'founded_year' => 1983,
                ]),
            ],

            // Energy Companies
            [
                'name' => 'ExxonMobil Corporation',
                'industry_id' => $energyId,
                'email' => 'info@exxonmobil.com',
                'website' => 'exxonmobil.com',
                'phone' => '+1 (972) 940-6000',
                'address' => '5959 Las Colinas Boulevard',
                'city' => 'Irving',
                'region' => 'Texas',
                'postal_code' => '75039',
                'country' => 'United States',
                'employee_count' => 62000,
                'annual_revenue' => 334700000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/exxonmobil',
                    'twitter' => '@ExxonMobil',
                    'founded_year' => 1999,
                ]),
            ],
            [
                'name' => 'Chevron Corporation',
                'industry_id' => $energyId,
                'email' => 'chevron@chevron.com',
                'website' => 'chevron.com',
                'phone' => '+1 (925) 842-1000',
                'address' => '6001 Bollinger Canyon Road',
                'city' => 'San Ramon',
                'region' => 'California',
                'postal_code' => '94583',
                'country' => 'United States',
                'employee_count' => 43846,
                'annual_revenue' => 200000000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/chevron',
                    'twitter' => '@Chevron',
                    'founded_year' => 1879,
                ]),
            ],

            // Aerospace Companies
            [
                'name' => 'Boeing Company',
                'industry_id' => $aerospaceId,
                'email' => 'contact@boeing.com',
                'website' => 'boeing.com',
                'phone' => '+1 (312) 544-2000',
                'address' => '100 North Riverside Plaza',
                'city' => 'Chicago',
                'region' => 'Illinois',
                'postal_code' => '60606',
                'country' => 'United States',
                'employee_count' => 171000,
                'annual_revenue' => 77794000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/boeing',
                    'twitter' => '@Boeing',
                    'founded_year' => 1916,
                ]),
            ],
            [
                'name' => 'Airbus SE',
                'industry_id' => $aerospaceId,
                'email' => 'contact@airbus.com',
                'website' => 'airbus.com',
                'phone' => '+33 5 61 93 33 33',
                'address' => '2 Rond-Point Emile Dewoitine',
                'city' => 'Toulouse',
                'region' => 'Occitanie',
                'postal_code' => '31700',
                'country' => 'France',
                'employee_count' => 134000,
                'annual_revenue' => 65446000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/airbus',
                    'twitter' => '@Airbus',
                    'founded_year' => 1970,
                ]),
            ],

            // Consulting Companies
            [
                'name' => 'Deloitte',
                'industry_id' => $consultingId,
                'email' => 'info@deloitte.com',
                'website' => 'deloitte.com',
                'phone' => '+1 (212) 492-4000',
                'address' => '30 Rockefeller Plaza',
                'city' => 'New York',
                'region' => 'New York',
                'postal_code' => '10112',
                'country' => 'United States',
                'employee_count' => 457000,
                'annual_revenue' => 64900000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/deloitte',
                    'twitter' => '@Deloitte',
                    'founded_year' => 1845,
                ]),
            ],
            [
                'name' => 'McKinsey & Company',
                'industry_id' => $consultingId,
                'email' => 'contact@mckinsey.com',
                'website' => 'mckinsey.com',
                'phone' => '+1 (212) 446-7000',
                'address' => '3 World Trade Center',
                'city' => 'New York',
                'region' => 'New York',
                'postal_code' => '10007',
                'country' => 'United States',
                'employee_count' => 45000,
                'annual_revenue' => 16000000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/mckinsey',
                    'twitter' => '@McKinsey',
                    'founded_year' => 1926,
                ]),
            ],
        ];

        foreach ($companies as $companyData) {
            Company::create($companyData);
        }
    }
}
