<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\CompanyIndustry;
use Illuminate\Database\Seeder;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get industry IDs
        $technologyId = CompanyIndustry::where('slug', 'technology')->first()?->id;
        $automotiveId = CompanyIndustry::where('slug', 'automotive')->first()?->id;
        $entertainmentId = CompanyIndustry::where('slug', 'entertainment')->first()?->id;
        $retailId = CompanyIndustry::where('slug', 'retail')->first()?->id;
        $foodBeverageId = CompanyIndustry::where('slug', 'food-beverage')->first()?->id;
        $apparelId = CompanyIndustry::where('slug', 'fashion')->first()?->id;
        $bankingId = CompanyIndustry::where('slug', 'banking')->first()?->id;
        $pharmaceuticalsId = CompanyIndustry::where('slug', 'pharmaceuticals')->first()?->id;
        $telecomId = CompanyIndustry::where('slug', 'telecommunications')->first()?->id;
        $energyId = CompanyIndustry::where('slug', 'energy')->first()?->id;
        $aerospaceId = CompanyIndustry::where('slug', 'aerospace')->first()?->id;
        $consultingId = CompanyIndustry::where('slug', 'consulting')->first()?->id;

        $companies = [
            // Technology Companies
            [
                'name' => 'ARM Holdings',
                'industry_id' => $technologyId,
                'email' => 'info@arm.com',
                'website' => 'arm.com',
                'phone' => '+44 (0)1223 400400',
                'address' => '110 Fulbourn Road',
                'city' => 'Cambridge',
                'region' => 'Cambridgeshire',
                'postal_code' => 'CB1 9NJ',
                'country' => 'United Kingdom',
                'employee_count' => 6000,
                'annual_revenue' => 2680000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/arm',
                    'twitter' => '@Arm',
                    'founded_year' => 1990,
                ]),
            ],
            [
                'name' => 'Sage Group',
                'industry_id' => $technologyId,
                'email' => 'info@sage.com',
                'website' => 'sage.com',
                'phone' => '+44 (0)191 294 3000',
                'address' => 'North Park',
                'city' => 'Newcastle upon Tyne',
                'region' => 'Tyne and Wear',
                'postal_code' => 'NE13 9AA',
                'country' => 'United Kingdom',
                'employee_count' => 12000,
                'annual_revenue' => 2180000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/sage-software',
                    'twitter' => '@SageUK',
                    'founded_year' => 1981,
                ]),
            ],
            [
                'name' => 'Raspberry Pi Ltd',
                'industry_id' => $technologyId,
                'email' => 'info@raspberrypi.com',
                'website' => 'raspberrypi.com',
                'phone' => '+44 (0)1223 322633',
                'address' => 'Maurice Wilkes Building, St Johns Innovation Park',
                'city' => 'Cambridge',
                'region' => 'Cambridgeshire',
                'postal_code' => 'CB4 0DS',
                'country' => 'United Kingdom',
                'employee_count' => 300,
                'annual_revenue' => 265000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/raspberry-pi',
                    'twitter' => '@Raspberry_Pi',
                    'founded_year' => 2012,
                ]),
            ],
            [
                'name' => 'Sophos Ltd',
                'industry_id' => $technologyId,
                'email' => 'info@sophos.com',
                'website' => 'sophos.com',
                'phone' => '+44 (0)1235 559933',
                'address' => 'The Pentagon, Abingdon Science Park',
                'city' => 'Abingdon',
                'region' => 'Oxfordshire',
                'postal_code' => 'OX14 3YP',
                'country' => 'United Kingdom',
                'employee_count' => 4000,
                'annual_revenue' => 1037000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/sophos',
                    'twitter' => '@Sophos',
                    'founded_year' => 1985,
                ]),
            ],

            // Automotive Companies
            [
                'name' => 'Rolls-Royce Motor Cars',
                'industry_id' => $automotiveId,
                'email' => 'enquiries@rolls-roycemotorcars.com',
                'website' => 'rolls-roycemotorcars.com',
                'phone' => '+44 (0)1243 525700',
                'address' => 'The Drive, Westhampnett',
                'city' => 'Chichester',
                'region' => 'West Sussex',
                'postal_code' => 'PO18 0SH',
                'country' => 'United Kingdom',
                'employee_count' => 2000,
                'annual_revenue' => 5200000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/rolls-royce-motor-cars',
                    'twitter' => '@RollsRoyceCars',
                    'founded_year' => 1904,
                ]),
            ],
            [
                'name' => 'Bentley Motors',
                'industry_id' => $automotiveId,
                'email' => 'customer.services@bentley.co.uk',
                'website' => 'bentleymotors.com',
                'phone' => '+44 (0)1270 259959',
                'address' => 'Pyms Lane',
                'city' => 'Crewe',
                'region' => 'Cheshire',
                'postal_code' => 'CW1 3PL',
                'country' => 'United Kingdom',
                'employee_count' => 4000,
                'annual_revenue' => 2450000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/bentley-motors',
                    'twitter' => '@BentleyMotors',
                    'founded_year' => 1919,
                ]),
            ],
            [
                'name' => 'Aston Martin Lagonda',
                'industry_id' => $automotiveId,
                'email' => 'customerservice@astonmartin.com',
                'website' => 'astonmartin.com',
                'phone' => '+44 (0)1926 644644',
                'address' => 'Banbury Road',
                'city' => 'Gaydon',
                'region' => 'Warwickshire',
                'postal_code' => 'CV35 0DB',
                'country' => 'United Kingdom',
                'employee_count' => 2500,
                'annual_revenue' => 1095000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/aston-martin-lagonda',
                    'twitter' => '@astonmartin',
                    'founded_year' => 1913,
                ]),
            ],
            [
                'name' => 'McLaren Automotive',
                'industry_id' => $automotiveId,
                'email' => 'customerservice@mclaren.com',
                'website' => 'cars.mclaren.com',
                'phone' => '+44 (0)1483 261000',
                'address' => 'McLaren Technology Centre, Chertsey Road',
                'city' => 'Woking',
                'region' => 'Surrey',
                'postal_code' => 'GU21 4YH',
                'country' => 'United Kingdom',
                'employee_count' => 3500,
                'annual_revenue' => 1800000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/mclaren-automotive',
                    'twitter' => '@McLarenAuto',
                    'founded_year' => 2010,
                ]),
            ],

            // Retail Companies
            [
                'name' => 'Tesco PLC',
                'industry_id' => $retailId,
                'email' => 'customer.service@tesco.co.uk',
                'website' => 'tesco.com',
                'phone' => '+44 (0)800 505555',
                'address' => 'Tesco House, Shire Park',
                'city' => 'Welwyn Garden City',
                'region' => 'Hertfordshire',
                'postal_code' => 'AL7 1GA',
                'country' => 'United Kingdom',
                'employee_count' => 330000,
                'annual_revenue' => 64760000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/tesco',
                    'twitter' => '@Tesco',
                    'founded_year' => 1919,
                ]),
            ],
            [
                'name' => 'Marks & Spencer',
                'industry_id' => $retailId,
                'email' => 'customer.services@marks-and-spencer.com',
                'website' => 'marksandspencer.com',
                'phone' => '+44 (0)333 014 8555',
                'address' => 'Waterside House, 35 North Wharf Road',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'W2 1NW',
                'country' => 'United Kingdom',
                'employee_count' => 65000,
                'annual_revenue' => 11934000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/marks-and-spencer',
                    'twitter' => '@MarksandSpencer',
                    'founded_year' => 1884,
                ]),
            ],
            [
                'name' => 'John Lewis Partnership',
                'industry_id' => $retailId,
                'email' => 'contact@johnlewis.co.uk',
                'website' => 'johnlewis.com',
                'phone' => '+44 (0)345 604 9049',
                'address' => '171 Victoria Street',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'SW1E 5NN',
                'country' => 'United Kingdom',
                'employee_count' => 78000,
                'annual_revenue' => 11904000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/john-lewis-partnership',
                    'twitter' => '@JohnLewisRetail',
                    'founded_year' => 1864,
                ]),
            ],
            [
                'name' => 'Next PLC',
                'industry_id' => $retailId,
                'email' => 'customer.relations@next.co.uk',
                'website' => 'next.co.uk',
                'phone' => '+44 (0)333 777 8000',
                'address' => 'Desford Road',
                'city' => 'Leicester',
                'region' => 'Leicestershire',
                'postal_code' => 'LE19 4AT',
                'country' => 'United Kingdom',
                'employee_count' => 43000,
                'annual_revenue' => 5107000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/next',
                    'twitter' => '@NextOfficial',
                    'founded_year' => 1982,
                ]),
            ],

            // Food & Beverage Companies
            [
                'name' => 'Diageo PLC',
                'industry_id' => $foodBeverageId,
                'email' => 'info@diageo.com',
                'website' => 'diageo.com',
                'phone' => '+44 (0)20 7927 5200',
                'address' => 'Lakeside Drive',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'NW10 7HQ',
                'country' => 'United Kingdom',
                'employee_count' => 28000,
                'annual_revenue' => 20253000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/diageo',
                    'twitter' => '@Diageo_News',
                    'founded_year' => 1997,
                ]),
            ],
            [
                'name' => 'Greggs PLC',
                'industry_id' => $foodBeverageId,
                'email' => 'customer.relations@greggs.co.uk',
                'website' => 'greggs.co.uk',
                'phone' => '+44 (0)191 281 7721',
                'address' => 'Greggs House, Quorum Business Park',
                'city' => 'Newcastle upon Tyne',
                'region' => 'Tyne and Wear',
                'postal_code' => 'NE12 8BU',
                'country' => 'United Kingdom',
                'employee_count' => 25000,
                'annual_revenue' => 1513000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/greggs',
                    'twitter' => '@GreggsOfficial',
                    'founded_year' => 1939,
                ]),
            ],
            [
                'name' => 'Pret A Manger',
                'industry_id' => $foodBeverageId,
                'email' => 'customer.service@pret.com',
                'website' => 'pret.co.uk',
                'phone' => '+44 (0)20 7932 5000',
                'address' => '75B, Verde',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'E14 9SQ',
                'country' => 'United Kingdom',
                'employee_count' => 13000,
                'annual_revenue' => 879000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/pret-a-manger',
                    'twitter' => '@Pret',
                    'founded_year' => 1983,
                ]),
            ],
            [
                'name' => 'Whitbread PLC',
                'industry_id' => $foodBeverageId,
                'email' => 'customer.relations@whitbread.com',
                'website' => 'whitbread.co.uk',
                'phone' => '+44 (0)1582 424200',
                'address' => 'Whitbread Court, Houghton Hall Business Park',
                'city' => 'Dunstable',
                'region' => 'Bedfordshire',
                'postal_code' => 'LU5 5XE',
                'country' => 'United Kingdom',
                'employee_count' => 52000,
                'annual_revenue' => 2913000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/whitbread',
                    'twitter' => '@Whitbread_PLC',
                    'founded_year' => 1742,
                ]),
            ],

            // Fashion/Apparel Companies
            [
                'name' => 'Burberry Group',
                'industry_id' => $apparelId,
                'email' => 'contact@burberry.com',
                'website' => 'burberry.com',
                'phone' => '+44 (0)20 3367 3000',
                'address' => 'Horseferry House, Horseferry Road',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'SW1P 2AW',
                'country' => 'United Kingdom',
                'employee_count' => 9000,
                'annual_revenue' => 2913000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/burberry',
                    'twitter' => '@Burberry',
                    'founded_year' => 1856,
                ]),
            ],
            [
                'name' => 'Mulberry Group',
                'industry_id' => $apparelId,
                'email' => 'customer.service@mulberry.com',
                'website' => 'mulberry.com',
                'phone' => '+44 (0)1761 234500',
                'address' => 'The Rookery',
                'city' => 'Chilcompton',
                'region' => 'Somerset',
                'postal_code' => 'BA3 4EH',
                'country' => 'United Kingdom',
                'employee_count' => 1400,
                'annual_revenue' => 152000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/mulberry',
                    'twitter' => '@MulberryEngland',
                    'founded_year' => 1971,
                ]),
            ],
            [
                'name' => 'Barbour',
                'industry_id' => $apparelId,
                'email' => 'customer.services@barbour.com',
                'website' => 'barbour.com',
                'phone' => '+44 (0)191 455 4444',
                'address' => 'Simonside, South Shields',
                'city' => 'South Shields',
                'region' => 'Tyne and Wear',
                'postal_code' => 'NE34 9PD',
                'country' => 'United Kingdom',
                'employee_count' => 1500,
                'annual_revenue' => 245000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/j-barbour-and-sons',
                    'twitter' => '@Barbour',
                    'founded_year' => 1894,
                ]),
            ],

            // Banking Companies
            [
                'name' => 'HSBC Holdings',
                'industry_id' => $bankingId,
                'email' => 'customer.service@hsbc.co.uk',
                'website' => 'hsbc.co.uk',
                'phone' => '+44 (0)345 740 4404',
                'address' => '8 Canada Square',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'E14 5HQ',
                'country' => 'United Kingdom',
                'employee_count' => 220000,
                'annual_revenue' => 65000000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/hsbc',
                    'twitter' => '@HSBC_UK',
                    'founded_year' => 1865,
                ]),
            ],
            [
                'name' => 'Barclays PLC',
                'industry_id' => $bankingId,
                'email' => 'service@barclays.co.uk',
                'website' => 'barclays.co.uk',
                'phone' => '+44 (0)345 734 5345',
                'address' => '1 Churchill Place',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'E14 5HP',
                'country' => 'United Kingdom',
                'employee_count' => 85000,
                'annual_revenue' => 27197000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/barclays',
                    'twitter' => '@BarclaysUK',
                    'founded_year' => 1690,
                ]),
            ],
            [
                'name' => 'Lloyds Banking Group',
                'industry_id' => $bankingId,
                'email' => 'customer.services@lloydsbanking.com',
                'website' => 'lloydsbankinggroup.com',
                'phone' => '+44 (0)345 300 0000',
                'address' => '25 Gresham Street',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'EC2V 7HN',
                'country' => 'United Kingdom',
                'employee_count' => 65000,
                'annual_revenue' => 18634000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/lloyds-banking-group',
                    'twitter' => '@LloydsBanking',
                    'founded_year' => 1695,
                ]),
            ],
            [
                'name' => 'NatWest Group',
                'industry_id' => $bankingId,
                'email' => 'help@natwest.com',
                'website' => 'natwestgroup.com',
                'phone' => '+44 (0)345 788 8444',
                'address' => '250 Bishopsgate',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'EC2M 4AA',
                'country' => 'United Kingdom',
                'employee_count' => 58000,
                'annual_revenue' => 14013000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/natwest-group',
                    'twitter' => '@NatWest',
                    'founded_year' => 1968,
                ]),
            ],

            // Pharmaceuticals Companies
            [
                'name' => 'AstraZeneca PLC',
                'industry_id' => $pharmaceuticalsId,
                'email' => 'information.centre@astrazeneca.com',
                'website' => 'astrazeneca.com',
                'phone' => '+44 (0)20 3749 5000',
                'address' => '1 Francis Crick Avenue',
                'city' => 'Cambridge',
                'region' => 'Cambridgeshire',
                'postal_code' => 'CB2 0AA',
                'country' => 'United Kingdom',
                'employee_count' => 89700,
                'annual_revenue' => 44350000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/astrazeneca',
                    'twitter' => '@AstraZeneca',
                    'founded_year' => 1999,
                ]),
            ],
            [
                'name' => 'GlaxoSmithKline',
                'industry_id' => $pharmaceuticalsId,
                'email' => 'customer.contact@gsk.com',
                'website' => 'gsk.com',
                'phone' => '+44 (0)20 8047 5000',
                'address' => '980 Great West Road',
                'city' => 'Brentford',
                'region' => 'Greater London',
                'postal_code' => 'TW8 9GS',
                'country' => 'United Kingdom',
                'employee_count' => 69000,
                'annual_revenue' => 34147000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/glaxosmithkline',
                    'twitter' => '@GSK',
                    'founded_year' => 2000,
                ]),
            ],

            // Telecommunications Companies
            [
                'name' => 'BT Group PLC',
                'industry_id' => $telecomId,
                'email' => 'bt.enquiries@bt.com',
                'website' => 'bt.com',
                'phone' => '+44 (0)800 800 150',
                'address' => '1 Braham Street',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'E1 8EE',
                'country' => 'United Kingdom',
                'employee_count' => 99700,
                'annual_revenue' => 20670000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/bt',
                    'twitter' => '@BT_UK',
                    'founded_year' => 1846,
                ]),
            ],
            [
                'name' => 'Vodafone Group',
                'industry_id' => $telecomId,
                'email' => 'customer.services@vodafone.com',
                'website' => 'vodafone.co.uk',
                'phone' => '+44 (0)333 304 0191',
                'address' => 'Vodafone House, The Connection',
                'city' => 'Newbury',
                'region' => 'Berkshire',
                'postal_code' => 'RG14 2FN',
                'country' => 'United Kingdom',
                'employee_count' => 96506,
                'annual_revenue' => 45700000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/vodafone',
                    'twitter' => '@VodafoneUK',
                    'founded_year' => 1991,
                ]),
            ],

            // Energy Companies
            [
                'name' => 'BP PLC',
                'industry_id' => $energyId,
                'email' => 'bpcomms@bp.com',
                'website' => 'bp.com',
                'phone' => '+44 (0)20 7496 4000',
                'address' => '1 St James Square',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'SW1Y 4PD',
                'country' => 'United Kingdom',
                'employee_count' => 66800,
                'annual_revenue' => 248900000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/bp',
                    'twitter' => '@BP_plc',
                    'founded_year' => 1909,
                ]),
            ],
            [
                'name' => 'Shell PLC',
                'industry_id' => $energyId,
                'email' => 'shell.com@shell.com',
                'website' => 'shell.com',
                'phone' => '+44 (0)20 7934 1234',
                'address' => 'Shell Centre',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'SE1 7NA',
                'country' => 'United Kingdom',
                'employee_count' => 93000,
                'annual_revenue' => 316614000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/shell',
                    'twitter' => '@Shell',
                    'founded_year' => 1907,
                ]),
            ],

            // Aerospace Companies
            [
                'name' => 'Rolls-Royce Holdings',
                'industry_id' => $aerospaceId,
                'email' => 'enquiries@rolls-royce.com',
                'website' => 'rolls-royce.com',
                'phone' => '+44 (0)1332 242424',
                'address' => '62 Buckingham Gate',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'SW1E 6AT',
                'country' => 'United Kingdom',
                'employee_count' => 42000,
                'annual_revenue' => 16905000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/rolls-royce',
                    'twitter' => '@RollsRoyce',
                    'founded_year' => 1906,
                ]),
            ],
            [
                'name' => 'BAE Systems',
                'industry_id' => $aerospaceId,
                'email' => 'customer.contact@baesystems.com',
                'website' => 'baesystems.com',
                'phone' => '+44 (0)1252 373232',
                'address' => 'Stirling Square, 6 Carlton Gardens',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'SW1Y 5AD',
                'country' => 'United Kingdom',
                'employee_count' => 93100,
                'annual_revenue' => 25300000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/bae-systems',
                    'twitter' => '@BAESystemsplc',
                    'founded_year' => 1999,
                ]),
            ],

            // Consulting Companies
            [
                'name' => 'PricewaterhouseCoopers UK',
                'industry_id' => $consultingId,
                'email' => 'contactus@pwc.com',
                'website' => 'pwc.co.uk',
                'phone' => '+44 (0)20 7583 5000',
                'address' => '1 Embankment Place',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'WC2N 6RH',
                'country' => 'United Kingdom',
                'employee_count' => 22000,
                'annual_revenue' => 5100000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/pwc-uk',
                    'twitter' => '@PwC_UK',
                    'founded_year' => 1849,
                ]),
            ],
            [
                'name' => 'KPMG UK',
                'industry_id' => $consultingId,
                'email' => 'contact@kpmg.co.uk',
                'website' => 'kpmg.com/uk',
                'phone' => '+44 (0)20 7311 1000',
                'address' => '15 Canada Square',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'E14 5GL',
                'country' => 'United Kingdom',
                'employee_count' => 16000,
                'annual_revenue' => 2890000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/kpmg-uk',
                    'twitter' => '@KPMGUK',
                    'founded_year' => 1870,
                ]),
            ],

            // Entertainment Companies
            [
                'name' => 'BBC Studios',
                'industry_id' => $entertainmentId,
                'email' => 'info@bbcstudios.com',
                'website' => 'bbcstudios.com',
                'phone' => '+44 (0)20 8433 2000',
                'address' => '1 Television Centre, 101 Wood Lane',
                'city' => 'London',
                'region' => 'Greater London',
                'postal_code' => 'W12 7FA',
                'country' => 'United Kingdom',
                'employee_count' => 2900,
                'annual_revenue' => 1630000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/bbc-studios',
                    'twitter' => '@BBCStudios',
                    'founded_year' => 2018,
                ]),
            ],
            [
                'name' => 'Sky UK',
                'industry_id' => $entertainmentId,
                'email' => 'customer.service@sky.uk',
                'website' => 'sky.com',
                'phone' => '+44 (0)333 100 0333',
                'address' => 'Grant Way',
                'city' => 'Isleworth',
                'region' => 'Greater London',
                'postal_code' => 'TW7 5QD',
                'country' => 'United Kingdom',
                'employee_count' => 31000,
                'annual_revenue' => 18495000000,
                'is_real' => true,
                'meta' => json_encode([
                    'linkedin' => 'https://linkedin.com/company/sky',
                    'twitter' => '@SkyUK',
                    'founded_year' => 1990,
                ]),
            ],
        ];

        foreach ($companies as $companyData) {
            Company::firstOrCreate($companyData);
        }
    }
}
