<?php

namespace Database\Seeders;

use App\Models\Pipeline;
use App\Models\PipelineStage;
use App\Models\User;
use Illuminate\Database\Seeder;

class PipelineStageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (PipelineStage::exists()) {
            $this->command->info('Pipeline Stages already seeded, skipping...');
            return;
        }

        $users = User::all();
        $pipelines = Pipeline::all();
        
        if ($pipelines->isEmpty()) {
            $this->command->warn('No pipelines found. Please run PipelineSeeder first.');
            return;
        }

        if ($users->isEmpty()) {
            $this->command->warn('No users found. Please run UserSeeder first.');
            return;
        }

        // Get pipeline IDs
        $salesPipelineId = Pipeline::where('entity_type', 'deal')->where('name', 'Sales Pipeline')->first()?->id;
        $orderPipelineId = Pipeline::where('entity_type', 'order')->where('name', 'Order Fulfillment')->first()?->id;
        $ticketPipelineId = Pipeline::where('entity_type', 'ticket')->where('name', 'Support Workflow')->first()?->id;
        $projectPipelineId = Pipeline::where('entity_type', 'project')->where('name', 'Project Delivery')->first()?->id;
        $taskPipelineId = Pipeline::where('entity_type', 'task')->where('name', 'Task Workflow')->first()?->id;
        $candidatePipelineId = Pipeline::where('entity_type', 'candidate')->where('name', 'Recruitment Process')->first()?->id;
        $quotePipelineId = Pipeline::where('entity_type', 'quote')->where('name', 'Quote Process')->first()?->id;

        $stages = [
            // Sales Pipeline Stages
            [
                'pipeline_id' => $salesPipelineId,
                'name' => 'Lead',
                'colour' => '#94A3B8',
                'position' => 0,
                'probability' => 10,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $salesPipelineId,
                'name' => 'Qualified',
                'colour' => '#60A5FA',
                'position' => 1,
                'probability' => 25,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $salesPipelineId,
                'name' => 'Proposal',
                'colour' => '#FBBF24',
                'position' => 2,
                'probability' => 50,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $salesPipelineId,
                'name' => 'Negotiation',
                'colour' => '#FB923C',
                'position' => 3,
                'probability' => 75,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $salesPipelineId,
                'name' => 'Closed Won',
                'colour' => '#34D399',
                'position' => 4,
                'probability' => 100,
                'is_terminal' => true,
                'terminal_type' => 'won',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $salesPipelineId,
                'name' => 'Closed Lost',
                'colour' => '#EF4444',
                'position' => 5,
                'probability' => 0,
                'is_terminal' => true,
                'terminal_type' => 'lost',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],

            // Order Fulfillment Stages
            [
                'pipeline_id' => $orderPipelineId,
                'name' => 'Pending',
                'colour' => '#94A3B8',
                'position' => 0,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => 24,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $orderPipelineId,
                'name' => 'Processing',
                'colour' => '#60A5FA',
                'position' => 1,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => 48,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $orderPipelineId,
                'name' => 'Shipped',
                'colour' => '#FBBF24',
                'position' => 2,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $orderPipelineId,
                'name' => 'Delivered',
                'colour' => '#34D399',
                'position' => 3,
                'probability' => null,
                'is_terminal' => true,
                'terminal_type' => 'completed',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $orderPipelineId,
                'name' => 'Cancelled',
                'colour' => '#EF4444',
                'position' => 4,
                'probability' => null,
                'is_terminal' => true,
                'terminal_type' => 'cancelled',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],

            // Support Ticket Stages
            [
                'pipeline_id' => $ticketPipelineId,
                'name' => 'New',
                'colour' => '#94A3B8',
                'position' => 0,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => 2,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $ticketPipelineId,
                'name' => 'Assigned',
                'colour' => '#60A5FA',
                'position' => 1,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => 4,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $ticketPipelineId,
                'name' => 'In Progress',
                'colour' => '#FBBF24',
                'position' => 2,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => 24,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $ticketPipelineId,
                'name' => 'Pending Customer',
                'colour' => '#FB923C',
                'position' => 3,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $ticketPipelineId,
                'name' => 'Resolved',
                'colour' => '#34D399',
                'position' => 4,
                'probability' => null,
                'is_terminal' => true,
                'terminal_type' => 'completed',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $ticketPipelineId,
                'name' => 'Closed',
                'colour' => '#64748B',
                'position' => 5,
                'probability' => null,
                'is_terminal' => true,
                'terminal_type' => 'completed',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],

            // Project Delivery Stages
            [
                'pipeline_id' => $projectPipelineId,
                'name' => 'Planning',
                'colour' => '#94A3B8',
                'position' => 0,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $projectPipelineId,
                'name' => 'In Progress',
                'colour' => '#60A5FA',
                'position' => 1,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $projectPipelineId,
                'name' => 'Review',
                'colour' => '#FBBF24',
                'position' => 2,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => true,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $projectPipelineId,
                'name' => 'Testing',
                'colour' => '#FB923C',
                'position' => 3,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $projectPipelineId,
                'name' => 'Delivered',
                'colour' => '#34D399',
                'position' => 4,
                'probability' => null,
                'is_terminal' => true,
                'terminal_type' => 'completed',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $projectPipelineId,
                'name' => 'On Hold',
                'colour' => '#64748B',
                'position' => 5,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $projectPipelineId,
                'name' => 'Cancelled',
                'colour' => '#EF4444',
                'position' => 6,
                'probability' => null,
                'is_terminal' => true,
                'terminal_type' => 'cancelled',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],

            // Task Workflow Stages
            [
                'pipeline_id' => $taskPipelineId,
                'name' => 'To Do',
                'colour' => '#94A3B8',
                'position' => 0,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $taskPipelineId,
                'name' => 'In Progress',
                'colour' => '#60A5FA',
                'position' => 1,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $taskPipelineId,
                'name' => 'Review',
                'colour' => '#FBBF24',
                'position' => 2,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $taskPipelineId,
                'name' => 'Done',
                'colour' => '#34D399',
                'position' => 3,
                'probability' => null,
                'is_terminal' => true,
                'terminal_type' => 'completed',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],

            // Recruitment Process Stages
            [
                'pipeline_id' => $candidatePipelineId,
                'name' => 'Applied',
                'colour' => '#94A3B8',
                'position' => 0,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $candidatePipelineId,
                'name' => 'Screening',
                'colour' => '#60A5FA',
                'position' => 1,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $candidatePipelineId,
                'name' => 'Interview',
                'colour' => '#FBBF24',
                'position' => 2,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $candidatePipelineId,
                'name' => 'Offer',
                'colour' => '#FB923C',
                'position' => 3,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => true,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $candidatePipelineId,
                'name' => 'Hired',
                'colour' => '#34D399',
                'position' => 4,
                'probability' => null,
                'is_terminal' => true,
                'terminal_type' => 'completed',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $candidatePipelineId,
                'name' => 'Rejected',
                'colour' => '#EF4444',
                'position' => 5,
                'probability' => null,
                'is_terminal' => true,
                'terminal_type' => 'rejected',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],

            // Quote Process Stages
            [
                'pipeline_id' => $quotePipelineId,
                'name' => 'Draft',
                'colour' => '#94A3B8',
                'position' => 0,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $quotePipelineId,
                'name' => 'Sent',
                'colour' => '#60A5FA',
                'position' => 1,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $quotePipelineId,
                'name' => 'Under Review',
                'colour' => '#FBBF24',
                'position' => 2,
                'probability' => null,
                'is_terminal' => false,
                'terminal_type' => null,
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $quotePipelineId,
                'name' => 'Accepted',
                'colour' => '#34D399',
                'position' => 3,
                'probability' => null,
                'is_terminal' => true,
                'terminal_type' => 'won',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $quotePipelineId,
                'name' => 'Declined',
                'colour' => '#EF4444',
                'position' => 4,
                'probability' => null,
                'is_terminal' => true,
                'terminal_type' => 'lost',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
            [
                'pipeline_id' => $quotePipelineId,
                'name' => 'Expired',
                'colour' => '#64748B',
                'position' => 5,
                'probability' => null,
                'is_terminal' => true,
                'terminal_type' => 'cancelled',
                'sla_hours' => null,
                'requires_approval' => false,
                'is_real' => true,
                'created_by' => User::inRandomOrder()->first()?->id,
            ],
        ];

        $created = 0;

        foreach ($stages as $stageData) {
            if ($stageData['pipeline_id'] === null) {
                continue;
            }

            $stage = PipelineStage::firstOrCreate(
                [
                    'pipeline_id' => $stageData['pipeline_id'],
                    'name' => $stageData['name'],
                ],
                $stageData
            );

            if ($stage->wasRecentlyCreated) {
                $created++;
            }
        }

        $this->command->info("Created {$created} pipeline stages.");
    }
}
